In [4]:
import pandas as pd
import torch
import numpy as np
import matplotlib.pyplot as plt

# INTRODUCTION TO TENSORS

In [10]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
type(scalar)

torch.Tensor

In [12]:
scalar.item()

7

In [14]:
# Vector
vector = torch.tensor([7,7])

In [15]:
vector

tensor([7, 7])

In [17]:
vector.ndim #number of pairs of square brackets:) 

1

In [18]:
vector.shape

torch.Size([2])

In [21]:
# MATRIX
MATRIX = torch.tensor([[7,8],[1,2]])

In [22]:
MATRIX.ndim

2

In [23]:
MATRIX

tensor([[7, 8],
        [1, 2]])

In [24]:
MATRIX[0]

tensor([7, 8])

In [25]:
MATRIX.shape

torch.Size([2, 2])

In [28]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,4,5],[5,6,7]]])

In [29]:
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [30]:
TENSOR.shape 

torch.Size([1, 3, 3])

In [31]:
TENSOR.ndim

3

In [32]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

In [37]:
TENSOR[0][0][0]

tensor(1)