In [41]:
import pandas as pd
import torch
import numpy as np
import matplotlib.pyplot as plt

In [42]:
tensor_1 = torch.tensor([[[1,2,3]],[[4,5,6]]])

In [43]:
tensor_1.shape

torch.Size([2, 1, 3])

In [44]:
tensor_1

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [45]:
tensor_2 = torch.tensor([[[7,8,9]],[[10,11,12]]])

In [46]:
tensor_2.shape

torch.Size([2, 1, 3])

In [47]:
tensor_1 = tensor_1.reshape(2,3,1)

In [48]:
tensor_1

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

In [50]:
torch.matmul(tensor_1,tensor_2)

tensor([[[ 7,  8,  9],
         [14, 16, 18],
         [21, 24, 27]],

        [[40, 44, 48],
         [50, 55, 60],
         [60, 66, 72]]])