### Random Tensors

why random tensors?
they are important becuase the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.


In [2]:
# create a random tensors of size (3,4)
import pandas as pd
import torch
import numpy as np
import matplotlib.pyplot as plt


In [3]:
random_tensor = torch.rand(3,3)

In [4]:
random_tensor

tensor([[0.5762, 0.9213, 0.1784],
        [0.5387, 0.9191, 0.9761],
        [0.8715, 0.2670, 0.4416]])

In [5]:
random_tensor.ndim

2

In [6]:
# random tensor with similar shape to image tensor

In [7]:
random_image_size_tensor = torch.rand(size=(224,224,3))
#height,widht,color channel

In [11]:
# Creating tensor with all zero
zero  = torch.zeros(size=[3,4])

In [12]:
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
ones = torch.ones(size=[3,4])

In [15]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])