In [2]:
#torch.range()
import pandas as pd
import torch
import numpy as np
import matplotlib.pyplot as plt

In [5]:
tensor = torch.arange(2,9)

In [6]:
tensor

tensor([2, 3, 4, 5, 6, 7, 8])

In [10]:
MATRIX = torch.arange(1,10,3)

In [11]:
MATRIX

tensor([1, 4, 7])

In [12]:
# Creating tensors like:
tensor.shape

torch.Size([7])

In [13]:
ten_zeros = torch.zeros_like(input=MATRIX)

In [14]:
ten_zeros

tensor([0, 0, 0])