In [2]:
import pandas as pd
import torch
import numpy as np
import matplotlib.pyplot as plt

In [8]:
#float 32 tensor:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,device="cuda",requires_grad=False)

In [9]:
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [10]:
float_32_tensor.dtype

torch.float32

In [11]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [13]:
float_16_tensor.dtype

torch.float16

In [14]:
tensor = float_16_tensor*float_32_tensor

In [16]:
tensor = tensor.type(torch.float16)

In [17]:
tensor.dtype

torch.float16

In [22]:
int_32_tensor = torch.tensor([3,4,5],dtype=torch.int32,device="cuda")

In [23]:
int_32_tensor

tensor([3, 4, 5], device='cuda:0', dtype=torch.int32)

In [24]:
int_32_tensor.dtype

torch.int32

In [25]:
float_32_tensor*int_32_tensor

tensor([ 9., 24., 45.], device='cuda:0')

In [27]:
print("device:{int_32_tensor.device}")

NameError: name 'f' is not defined